### ISSUE TITLE
about sky-optimization

### ISSUE THREAD

**Issue by xiongzhu666** [tavihalperin/Neural-Egg-Seperation#1]
Hi，about your sky-optimization code,  I am very grateful for your nice python code and I had transfer the algorithm in c++ successfully based on your code. 
but you code didn't add the function of “Density estimation algorithm”，I am confused about "Density estimation". The Author only provide a formula.  could you provide some idea or simple python code??
                                                                                                                                   thanks, best regards

**Comment by tavihalperin** [comment]
this is not related to the guided filter, please ask the authors, in the repository
https://github.com/google/sky-optimization
